server:
  port: 8081
#jwt
jwt:
  access:
    expiration:
      milliseconds: 900000
  refresh:
    expiration:
      milliseconds: 3000000
  secret: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecucuresecuresecuresecure

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/email_verification_service
    username: root
    password: Ab@230596
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.elasticemail.com
    port: 2525
    username: depitaztech@gmail.com
    password: 72584702918749D99F8B5147B01B2361B498
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  redis:
    host: localhost
    port: 6379


## rabbitmq connection property
rabbitmq:
  queue:
    name: notification-queue
    reset-password: reset-password
    login-alert: login-alert-queue
  exchange:
    name: notification-exchange
    reset-password: reset-password
    login-alert: login-alert-exchange
  binding:
    key: binding-key
    reset-password-key: reset-password
    login-alert-key: login-alert-binding-key

paystack:
  secret-key: sk_test_03487c78f5c63bb483e06bbfc634b8f2eab2b665
  base-url: https://api.paystack.co/

