server:
  port: 8081
#jwt
jwt:
  access:
    expiration:
      milliseconds: 900000
  refresh:
    expiration:
      milliseconds: 3000000
  secret: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecucuresecuresecuresecure

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/email_verification_service
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.elasticemail.com
    port: 2525
    username: depitaztech@gmail.com
    password: 72584702918749D99F8B5147B01B2361B498
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

## rabbitmq connection property
rabbitmq:
  queue:
    email_queue: email_message_queue
    payment_queue: product_purchase_queue
  exchange:
    email_exchange: email_message_exchange
    payment_exchange: product_purchase_exchange
  binding:
    email_key: email_binding_key
    payment_key: product_purchase_binding_key

paystack:
  secret-key: sk_test_03487c78f5c63bb483e06bbfc634b8f2eab2b665
  base-url: https://api.paystack.co/

